<?php

class PdfThumbnailsPlugin
{
    
    /**
     * @var PdfThumbnailsPlugin
     */
    private static $instance;

    private function __construct()
    {
        add_action('wp_generate_attachment_metadata', array($this, 'onGenerateAttachmentMetadata'), 10, 2);
    }
    
    /**
     * Initiates plugin by attaching all events and hooks
     */
    public static function onInit()
    {
        if (!self::$instance) {
            self::$instance = new self;
        }
        return self::$instance;
    }
    
    /**
     * Generate thumbnail for PDF by reading first page and generating a thumbnail
     * image.
     * 
     * @param array $metadata
     * @param \WP_Post $postId
     * @return array $metadata
     */
    public function onGenerateAttachmentMetadata($metadata, $postId) {
        if ($this->isPdf($postId)) {
            $this->regenerateThumbnail($postId);
        }
        return $metadata;
    }
    
    private function isPdf($attachmentId)
    {
        return get_post_mime_type($attachmentId) === 'application/pdf';
    }
    
    /**
     * Delete existing thumbnail if generated by this plugin and generate a new 
     * one from PDF.
     * 
     * @param int $attachmentId
     */
    private function regenerateThumbnail($attachmentId)
    {
        $thumbnailId = get_post_thumbnail_id($attachmentId);
        if ($thumbnailId && get_post_meta($thumbnailId, 'PdfThumbnailsPlugin', true)) {
            wp_delete_attachment($thumbnailId, true);
        }
        $this->generateThumbnail($attachmentId);
    }
    
    private function generateThumbnail($attachmentId)
    {
        $filename = get_attached_file($attachmentId);
        $basename = str_replace('.', '-', basename($filename)) . '-image.jpg';
        $uploaded = $this->uploadThumbnail($basename, $this->getThumbnailBlob($filename));
        if ($uploaded['error'] === false) {
            $this->insertThumbnailAttachment($attachmentId, $uploaded);
        }
    }
    
    private function uploadThumbnail($filename, $blob)
    {
        return wp_upload_bits($filename, null, $blob);
    }
    
    private function getThumbnailBlob($filename)
    {
        $im = new \Imagick($filename . '[0]');
        $im->setImageFormat('jpg');
        return $im->getImageBlob();
    }
    
    private function insertThumbnailAttachment($attachmentId, $uploaded)
    {
        // Get the the original attachement
        $pdfAttachment = get_post($attachmentId);
        if (!$pdfAttachment) {
            return;
        }
        
        // Create thumbnail
        $attachment = array(
            'post_mime_type' => 'image/jpeg',
            'post_type' => 'attachment',
            'post_content' => '',
            'post_title' => $pdfAttachment->post_title . '-thumbnail',
            'post_parent' => $pdfAttachment->ID
        );
        $thumbnailId = wp_insert_attachment($attachment, $uploaded['file']);
        $thumbnailMetadata = wp_generate_attachment_metadata($thumbnailId, $uploaded['file']);
        wp_update_attachment_metadata($thumbnailId, $thumbnailMetadata);
        update_post_meta($attachmentId, '_thumbnail_id', $thumbnailId);
        
        // Mark generated thumbnails for future reference
        update_post_meta($thumbnailId, 'PdfThumbnailsPlugin', true);
    }
}
